name: main
on:
  push:
  pull_request:
    branches: [ "main" ]
jobs:
  build-project:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: astral-sh/ruff-action@v3
